_BASE_: "../Base-RCNN-FPN.yaml"
DATALOADER:
  COPY_PASTE: False
  COPY_PASTE_RATE: 1.0
  VISUALIZE_COPY_PASTE: False
  COPY_PASTE_RANDOM_NUM: True
  COPY_PASTE_MIN_RATIO: 0.3
  COPY_PASTE_MAX_RATIO: 1.0
  NUM_WORKERS: 16
MODEL:
  PIXEL_MEAN: [0.592, 0.374, 0.285]
  PIXEL_STD: [0.262, 0.190, 0.1659]
  WEIGHTS: 'http://dl.fbaipublicfiles.com/cutler/checkpoints/dino_RN50_pretrain_d2_format.pkl'
  MASK_ON: False
  BACKBONE:
    FREEZE_AT: 0
  RESNETS:
    DEPTH: 50
    NORM: "SyncBN"
    STRIDE_IN_1X1: False
  FPN:
    NORM: "SyncBN"
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
  ROI_HEADS:
    NAME: CustomCascadeROIHeads
    NUM_CLASSES: 1
    SCORE_THRESH_TEST: 0.0
    POSITIVE_FRACTION: 0.4
    USE_DROPLOSS: True
    DROPLOSS_IOU_THRESH: 0.01
  RPN:
    POST_NMS_TOPK_TRAIN: 4000
    NMS_THRESH: 0.3
DATASETS:
  TRAIN: ("imagenet_train",)
  TEST: ("OUS-test", )
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.00001
  WEIGHT_DECAY: 0.0001
  MAX_ITER: 1000
  GAMMA: 0.01
  CLIP_GRADIENTS:
    CLIP_TYPE: norm
    CLIP_VALUE: 1.0
    ENABLED: true
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True
INPUT:
  MIN_SIZE_TRAIN: (240, 320, 480, 640)
  MAX_SIZE_TRAIN: 1024
  MASK_FORMAT: bitmask
  FORMAT: "RGB"
TEST:
  PRECISE_BN:
    ENABLED: True
    NUM_ITER: 200
  DETECTIONS_PER_IMAGE: 1
OUTPUT_DIR: "../../results/cutler_model"